### ISSUE TITLE
Can't OCR the PDF with image inside it

### ISSUE THREAD

**Issue by hoangdinhanphabe** [daita/files_fulltextsearch_tesseract#10]
Hi,
I already updated the version of the fulltextsearch tesseract up to version 1.2.2 and it works well on images file but i doesn't work on pdf file with image inside it. Is that a bug or haven't develop that feature yet ?
Thank you

**Comment by daita** [comment]
Please follow instruction from https://github.com/daita/files_fulltextsearch_tesseract/pull/8

**Comment by daita** [comment]
Also, there was a blog post about the installation process: https://daita.github.io/files-fulltextsearch-tesseract-ocr-pdf/

**Comment by hoangdinhanphabe** [comment]
It works, thank you
