### ISSUE TITLE
smartphone NextCloud App - fulltextsearch returning no results

### ISSUE THREAD

**Issue by gionxdata** [daita/files_fulltextsearch_tesseract#22]
Hi - I have installed a NextCloud server. The server has all the updates applied and your fulltext search add-on applied. Using a browser and logged into our NextCloud server I am able to successfully perform fulltext searchs on .txt .docx. .xls and .pdf documents.

To clarify if I was searching for the string 'fox' and it was within the content of the mentioned files types (.txt .docx. .xls and .pdf) I would get a successful search.

If I use a smartphone with the NextCloud app installed and used the search feature. I would not get any successful searches.

Is there a way to get this working? Who can I approach? If there is a cost involved would still be very interested in going forward.

Thanks Gio

**Comment by daita** [comment]
As of right now, the Nextcloud app does not use the fulltextsearch extension to search for files.
