### ISSUE TITLE
Limit the number of pages for PDF's

### ISSUE THREAD

**Issue by jacotec** [daita/files_fulltextsearch_tesseract#23]
As there is no real control what users are storing in their Nextcloud it'll be very handy to have the ability to limit the number of pages for a PDF to be OCRed.

Stored books with i.e. >500 pages will cause Tesseract to take forever to OCR them.

The ability to set a "max pages" parameter would be very handy. It could be configurable if the OCR is then limited to this number of pages (i.e. a 500 pages document with a max_pages of 20 will then still OCR the first 20 pages) or if PDF's with more pages than the limit will be ignored at all.

**Comment by daita** [comment]
I like this idea!

**Comment by jacotec** [comment]
@daita Awesome that you've added this that fast! :-))
Now I don't need to hack it in anymore.

Thanks a lot!
