### ISSUE TITLE
Can't OCR the PDF with image inside it

### ISSUE THREAD

**Issue by ciliusmp** [daita/files_fulltextsearch_tesseract#25]
It works fine for pictures but it does not work for PDFs with Pictures inside. 

Ubuntu 18.04
Nextcloud Version: 18.04
Fulltext Search: 1.4.1
Fulltext Elastic Search: 1.5.1
Full text Search Tesseract OCR: 1.4.1
PHP Version: 7.4.5
Memory Limit: 512 MB
Max Execution Time: 3600

Tesseract installed in /usr/share/tesseract-ocr/4.00

Tested with a TIFF File and it works. 

Followed the blog post and installed ImageMagick 6.0 and allowed it to read PDF in the policymap. 

I get no error when creating the index.

**Comment by wackazong** [comment]
I think you need to install ghostscript as well. Check the nextcloud log, mine said that a command failed that started with gs which is ghostscript.

**Comment by ciliusmp** [comment]
That did the trick, thanks!
