### ISSUE TITLE
Support for Nextcloud v19

### ISSUE THREAD

**Issue by rakekniven** [daita/files_fulltextsearch_tesseract#26]
Updater for NC19 RC3 says :

This app has no update available for NC 19

Can you please have a look?

Thank you

**Comment by jacotec** [comment]
@daita Did you forget this part of the Fulltext-Search tools? 😉

**Comment by NormandoHall** [comment]
We need a lot @daita

**Comment by jacotec** [comment]
Sorry to bother you @daita , but are there any plans for the NC19 update? This app is the last blocker for me for updating 3 instances to NC19 ...

**Comment by tensau** [comment]
Would be great to have this app for NC19, too.

**Comment by trendzetter** [comment]
@tensau @jacotec @NormandoHall @rakekniven I checked the content of the latest commit to the repository and it appears the code is now working with NC19. Just cloned it and installed, testing now. At least it doesn't crash NC19.

**Comment by daita** [comment]
Could not find the time to release yesterday. Should be available on app store now
