### ISSUE TITLE
Log is full with errors since update to 20.0.0

### ISSUE THREAD

**Issue by apg1980** [daita/files_fulltextsearch_tesseract#33]
Hello i am using nextcloud 20.0.3 with the latest update of fulltextsearch_tesseract.
My log is getting spammed with those messages:
`{"reqId":"VYwzcnRY1cPYmF6ehKDV","level":3,"time":"2020-12-11T21:45:50+01:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":{"Exception":"Error","Message":"Trying to get property 'useFileAsOutput' of non-object at /var/www/nextcloud/apps/files_fulltextsearch_tesseract/vendor/thiagoalessio/tesseract_ocr/src/TesseractOCR.php#42","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/files_fulltextsearch_tesseract/vendor/thiagoalessio/tesseract_ocr/src/TesseractOCR.php","line":42,"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"file":"/var/www/nextcloud/apps/files_fulltextsearch_tesseract/lib/Service/TesseractService.php","line":217,"function":"run","class":"thiagoalessio\\TesseractOCR\\TesseractOCR","type":"->"},{"file":"/var/www/nextcloud/apps/files_fulltextsearch_tesseract/lib/Service/TesseractService.php","line":194,"function":"ocrFileFromPath","class":"OCA\\Files_FullTextSearch_Tesseract\\Service\\TesseractService","type":"->"},{"file":"/var/www/nextcloud/apps/files_fulltextsearch_tesseract/lib/Service/TesseractService.php","line":169,"function":"ocrFile","class":"OCA\\Files_FullTextSearch_Tesseract\\Service\\TesseractService","type":"->"},{"file":"/var/www/nextcloud/apps/files_fulltextsearch_tesseract/lib/Service/TesseractService.php","line":121,"function":"extractContentUsingTesseractOCR","class":"OCA\\Files_FullTextSearch_Tesseract\\Service\\TesseractService","type":"->"},{"file":"/var/www/nextcloud/apps/files_fulltextsearch_tesseract/lib/Listeners/GenericListener.php","line":84,"function":"onFileIndexing","class":"OCA\\Files_FullTextSearch_Tesseract\\Service\\TesseractService","type":"->"},{"file":"/var/www/nextcloud/lib/private/EventDispatcher/ServiceEventListener.php","line":76,"function":"handle","class":"OCA\\Files_FullTextSearch_Tesseract\\Listeners\\GenericListener","type":"->"},{"file":"/var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":251,"function":"__invoke","class":"OC\\EventDispatcher\\ServiceEventListener","type":"->"},{"file":"/var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":73,"function":"callListeners","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/EventDispatcher/EventDispatcher.php","line":86,"function":"dispatch","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/EventDispatcher/EventDispatcher.php","line":98,"function":"dispatch","class":"OC\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/var/www/nextcloud/apps/files_fulltextsearch/lib/Service/ExtensionService.php","line":123,"function":"dispatchTyped","class":"OC\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/var/www/nextcloud/apps/files_fulltextsearch/lib/Service/ExtensionService.php","line":90,"function":"dispatch","class":"OCA\\Files_FullTextSearch\\Service\\ExtensionService","type":"->"},{"file":"/var/www/nextcloud/apps/files_fulltextsearch/lib/Service/FilesService.php","line":713,"function":"fileIndexing","class":"OCA\\Files_FullTextSearch\\Service\\ExtensionService","type":"->"},{"file":"/var/www/nextcloud/apps/files_fulltextsearch/lib/Service/FilesService.php","line":658,"function":"updateContentFromFile","class":"OCA\\Files_FullTextSearch\\Service\\FilesService","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/apps/files_fulltextsearch/lib/Service/FilesService.php","line":573,"function":"updateFilesDocumentFromFile","class":"OCA\\Files_FullTextSearch\\Service\\FilesService","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/apps/files_fulltextsearch/lib/Service/FilesService.php","line":621,"function":"generateDocumentFromIndex","class":"OCA\\Files_FullTextSearch\\Service\\FilesService","type":"->"},{"file":"/var/www/nextcloud/apps/files_fulltextsearch/lib/Provider/FilesProvider.php","line":291,"function":"updateDocument","class":"OCA\\Files_FullTextSearch\\Service\\FilesService","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/apps/fulltextsearch/lib/Service/IndexService.php","line":407,"function":"updateDocument","class":"OCA\\Files_FullTextSearch\\Provider\\FilesProvider","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/apps/fulltextsearch/lib/Cron/Index.php","line":134,"function":"updateDocument","class":"OCA\\FullTextSearch\\Service\\IndexService","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/apps/fulltextsearch/lib/Cron/Index.php","line":102,"function":"liveCycle","class":"OCA\\FullTextSearch\\Cron\\Index","type":"->"},{"file":"/var/www/nextcloud/lib/private/BackgroundJob/Job.php","line":52,"function":"run","class":"OCA\\FullTextSearch\\Cron\\Index","type":"->"},{"file":"/var/www/nextcloud/lib/private/BackgroundJob/TimedJob.php","line":59,"function":"execute","class":"OC\\BackgroundJob\\Job","type":"->"},{"file":"/var/www/nextcloud/cron.php","line":127,"function":"execute","class":"OC\\BackgroundJob\\TimedJob","type":"->"}],"File":"/var/www/nextcloud/lib/private/Log/ErrorHandler.php","Line":91,"CustomMessage":"--"},"userAgent":"--","version":"20.0.3.2","id":"5fd46f08efa2c"}`

`{"reqId":"VYwzcnRY1cPYmF6ehKDV","level":3,"time":"2020-12-11T21:45:50+01:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":{"Exception":"Error","Message":"Trying to get property 'executable' of non-object at /var/www/nextcloud/apps/files_fulltextsearch_tesseract/vendor/thiagoalessio/tesseract_ocr/src/TesseractOCR.php#26","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/files_fulltextsearch_tesseract/vendor/thiagoalessio/tesseract_ocr/src/TesseractOCR.php","line":26,"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"file":"/var/www/nextcloud/apps/files_fulltextsearch_tesseract/lib/Service/TesseractService.php","line":217,"function":"run","class":"thiagoalessio\\TesseractOCR\\TesseractOCR","type":"->"},{"file":"/var/www/nextcloud/apps/files_fulltextsearch_tesseract/lib/Service/TesseractService.php","line":194,"function":"ocrFileFromPath","class":"OCA\\Files_FullTextSearch_Tesseract\\Service\\TesseractService","type":"->"},{"file":"/var/www/nextcloud/apps/files_fulltextsearch_tesseract/lib/Service/TesseractService.php","line":169,"function":"ocrFile","class":"OCA\\Files_FullTextSearch_Tesseract\\Service\\TesseractService","type":"->"},{"file":"/var/www/nextcloud/apps/files_fulltextsearch_tesseract/lib/Service/TesseractService.php","line":121,"function":"extractContentUsingTesseractOCR","class":"OCA\\Files_FullTextSearch_Tesseract\\Service\\TesseractService","type":"->"},{"file":"/var/www/nextcloud/apps/files_fulltextsearch_tesseract/lib/Listeners/GenericListener.php","line":84,"function":"onFileIndexing","class":"OCA\\Files_FullTextSearch_Tesseract\\Service\\TesseractService","type":"->"},{"file":"/var/www/nextcloud/lib/private/EventDispatcher/ServiceEventListener.php","line":76,"function":"handle","class":"OCA\\Files_FullTextSearch_Tesseract\\Listeners\\GenericListener","type":"->"},{"file":"/var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":251,"function":"__invoke","class":"OC\\EventDispatcher\\ServiceEventListener","type":"->"},{"file":"/var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":73,"function":"callListeners","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/EventDispatcher/EventDispatcher.php","line":86,"function":"dispatch","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/EventDispatcher/EventDispatcher.php","line":98,"function":"dispatch","class":"OC\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/var/www/nextcloud/apps/files_fulltextsearch/lib/Service/ExtensionService.php","line":123,"function":"dispatchTyped","class":"OC\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/var/www/nextcloud/apps/files_fulltextsearch/lib/Service/ExtensionService.php","line":90,"function":"dispatch","class":"OCA\\Files_FullTextSearch\\Service\\ExtensionService","type":"->"},{"file":"/var/www/nextcloud/apps/files_fulltextsearch/lib/Service/FilesService.php","line":713,"function":"fileIndexing","class":"OCA\\Files_FullTextSearch\\Service\\ExtensionService","type":"->"},{"file":"/var/www/nextcloud/apps/files_fulltextsearch/lib/Service/FilesService.php","line":658,"function":"updateContentFromFile","class":"OCA\\Files_FullTextSearch\\Service\\FilesService","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/apps/files_fulltextsearch/lib/Service/FilesService.php","line":573,"function":"updateFilesDocumentFromFile","class":"OCA\\Files_FullTextSearch\\Service\\FilesService","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/apps/files_fulltextsearch/lib/Service/FilesService.php","line":621,"function":"generateDocumentFromIndex","class":"OCA\\Files_FullTextSearch\\Service\\FilesService","type":"->"},{"file":"/var/www/nextcloud/apps/files_fulltextsearch/lib/Provider/FilesProvider.php","line":291,"function":"updateDocument","class":"OCA\\Files_FullTextSearch\\Service\\FilesService","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/apps/fulltextsearch/lib/Service/IndexService.php","line":407,"function":"updateDocument","class":"OCA\\Files_FullTextSearch\\Provider\\FilesProvider","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/apps/fulltextsearch/lib/Cron/Index.php","line":134,"function":"updateDocument","class":"OCA\\FullTextSearch\\Service\\IndexService","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/apps/fulltextsearch/lib/Cron/Index.php","line":102,"function":"liveCycle","class":"OCA\\FullTextSearch\\Cron\\Index","type":"->"},{"file":"/var/www/nextcloud/lib/private/BackgroundJob/Job.php","line":52,"function":"run","class":"OCA\\FullTextSearch\\Cron\\Index","type":"->"},{"file":"/var/www/nextcloud/lib/private/BackgroundJob/TimedJob.php","line":59,"function":"execute","class":"OC\\BackgroundJob\\Job","type":"->"},{"file":"/var/www/nextcloud/cron.php","line":127,"function":"execute","class":"OC\\BackgroundJob\\TimedJob","type":"->"}],"File":"/var/www/nextcloud/lib/private/Log/ErrorHandler.php","Line":91,"CustomMessage":"--"},"userAgent":"--","version":"20.0.3.2","id":"5fd46f08efaa8"}`

**Comment by ShinjiLE** [comment]
This is really painful for me . It overwrite every entry at the search database in elasticsearch with a 0 Byte entry . All the hundreds  hour of CPU time for OCR are useless now . Is there really no solution ?

**Comment by f0ma85** [comment]
For me, the only salvation was going back to the previous version. Everything works fine in it.

**Comment by daita** [comment]
i'll try to have a look to this issue as soon as possible

**Comment by daita** [comment]
> I have run the test to ensure tesseract also works by using the demo images in the wiki.

what do you mean ? which images ?

**Comment by Davr3n** [comment]
> > I have run the test to ensure tesseract also works by using the demo images in the wiki.
> 
> what do you mean ? which images ?

I am unable to find the thread but it was either for this project or the fulltextsearch project where some of the suggestions mentioned for that issue were to test tesseract via command line. 

The test images linked in that project were located @ tesseract-for-php

**Comment by daita** [comment]
quick fix: `composer require "thiagoalessio/tesseract_ocr:2.4.0"` to run in the folder of the apps (apps/files_fulltextsearch_tesseract)

**Comment by Davr3n** [comment]
> composer require "thiagoalessio/tesseract_ocr:2.4.0"

Still no luck, the command returns the below error when I try to run it, any ideas?

**username**@**hostname**:/var/www/html/nextcloud/apps/files_fulltextsearch_tesseract$ sudo -u www-data composer require "thiagoalessio/tesseract_ocr:2.4.0"                                                                          [sudo] password for me:
Cannot create cache directory /var/www/.composer/cache/repo/https---repo.packagist.org/, or directory is not writable. Proceeding without cache
Cannot create cache directory /var/www/.composer/cache/files/, or directory is not writable. Proceeding without cache

In ArrayLoader.php line 44:

  Unknown package has no name defined ([{"name":"daita\/my-small-php-tools","version":"dev-master","version_normalized":"dev-master","source":{"type":"git","url":"https:\/\/github.com\/daita\/my-small-php-tool
  s.git","reference":"844b10da6abf50044ae9c40120cb5b927352bd95"},"dist":{"type":"zip","url":"https:\/\/api.github.com\/repos\/daita\/my-small-php-tools\/zipball\/844b10da6abf50044ae9c40120cb5b927352bd95","refe
  rence":"844b10da6abf50044ae9c40120cb5b927352bd95","shasum":""},"require":{"php":"^7.0"},"time":"2020-12-02T14:37:02+00:00","default-branch":true,"type":"library","installation-source":"source","autoload":{"p
  sr-4":{"daita\\MySmallPhpTools\\":"lib\/"}},"notification-url":"https:\/\/packagist.org\/downloads\/","license":["AGPL-3.0-or-later"],"authors":[{"name":"Maxence Lange","email":"maxence@artificial-owl.com"}]
  ,"description":"My small PHP Tools","support":{"issues":"https:\/\/github.com\/daita\/my-small-php-tools\/issues","source":"https:\/\/github.com\/daita\/my-small-php-tools\/tree\/master"},"install-path":"..\
  /daita\/my-small-php-tools"},{"name":"spatie\/pdf-to-image","version":"1.8.1","version_normalized":"1.8.1.0","source":{"type":"git","url":"https:\/\/github.com\/spatie\/pdf-to-image.git","reference":"f33afc9
  2ff7bff272fa6a9ba1cc335e96c57eb26"},"dist":{"type":"zip","url":"https:\/\/api.github.com\/repos\/spatie\/pdf-to-image\/zipball\/f33afc92ff7bff272fa6a9ba1cc335e96c57eb26","reference":"f33afc92ff7bff272fa6a9ba
  1cc335e96c57eb26","shasum":""},"require":{"ext-imagick":"*","php":"^7.0"},"require-dev":{"phpunit\/phpunit":"^6.2"},"time":"2018-07-02T09:30:32+00:00","type":"library","installation-source":"dist","autoload"
  :{"psr-4":{"Spatie\\PdfToImage\\":"src"}},"notification-url":"https:\/\/packagist.org\/downloads\/","license":["MIT"],"authors":[{"name":"Freek Van der Herten","email":"freek@spatie.be","homepage":"https:\/\
  /spatie.be","role":"Developer"}],"description":"Convert a pdf to an image","homepage":"https:\/\/github.com\/spatie\/pdf-to-image","keywords":["convert","image","pdf","pdf-to-image","spatie"],"support":{"iss
  ues":"https:\/\/github.com\/spatie\/pdf-to-image\/issues","source":"https:\/\/github.com\/spatie\/pdf-to-image\/tree\/master"},"install-path":"..\/spatie\/pdf-to-image"},{"name":"thiagoalessio\/tesseract_ocr
  ","version":"2.9.5","version_normalized":"2.9.5.0","source":{"type":"git","url":"https:\/\/github.com\/thiagoalessio\/tesseract-ocr-for-php.git","reference":"82cfd7879d6158be3098714f1d5c860f344a0e29"},"dist"
  :{"type":"zip","url":"https:\/\/api.github.com\/repos\/thiagoalessio\/tesseract-ocr-for-php\/zipball\/82cfd7879d6158be3098714f1d5c860f344a0e29","reference":"82cfd7879d6158be3098714f1d5c860f344a0e29","shasum"
  :""},"require":{"php":"^5.3 || ^7.0 || ^8.0"},"require-dev":{"phpunit\/php-code-coverage":"^2.2.4 || ^9.0.0"},"time":"2020-12-07T18:48:58+00:00","type":"library","installation-source":"dist","autoload":{"psr
  -4":{"thiagoalessio\\TesseractOCR\\":"src\/"}},"notification-url":"https:\/\/packagist.org\/downloads\/","license":["MIT"],"authors":[{"name":"thiagoalessio","email":"thiagoalessio@me.com"}],"description":"A
   wrapper to work with Tesseract OCR inside PHP.","keywords":["OCR","Tesseract","text recognition"],"support":{"irc":"irc:\/\/irc.freenode.net\/tesseract-ocr-for-php","issues":"https:\/\/github.com\/thiagoale
  ssio\/tesseract-ocr-for-php\/issues","source":"https:\/\/github.com\/thiagoalessio\/tesseract-ocr-for-php"},"install-path":"..\/thiagoalessio\/tesseract_ocr"}]).

**Comment by daita** [comment]
20.0.1 is available and should fix those issues

**Comment by ShinjiLE** [comment]
Thank you very much for the fix.
This app is really useful for me . Please keep on developing they .

**Comment by Davr3n** [comment]
> 20.0.1 is available and should fix those issues

Thanks a million, the fix is working just as expected and I appreciate the effort you put into this project.

On a side note, should this include images into the index or is it just office/pdfs?

**Comment by daita** [comment]
When the app is enabled, texts on image are ocr by default, yes.
