### ISSUE TITLE
Can PDFs be "OCRed" with this plugin?

### ISSUE THREAD

**Issue by josemaria-tcm** [daita/files_fulltextsearch_tesseract#5]
Hello.

I can't find any documentation about which file types are "OCRed" by tessereact-ocr and this plugin. So far JPG files are automatically processed in my tests, but scanned documents as PDF are not. I don't know if it is a software limitation, wrong configuration or  bug.

Are PDFs supposed to be processed by this plugin? If no, will it do it in the future or is a limitation of tesseract-ocr?

Would be nice to be able to index existing PDF documents .

Thank you very much.

**Comment by daita** [comment]
no, this need to be implemented into files_fulltextsearch_tesseract
