### ISSUE TITLE
occ commands

### ISSUE THREAD

**Issue by ggeorgg** [daita/files_fulltextsearch_tesseract#6]
Hi, 
I am about to edit/create a bash file for installing fulltextsearch for nextcloud and I want to include tesseract. 
I have succesfully installed fulltextsearch.
I have installed the nextcloud apps fulltextsearch, fulltextsearch_elasticsearch, files_fulltextsearch. 
I ran `sudo apt-get install -y tesseract-ocr tesseract-ocr-deu tesseract-ocr-eng` on my ubuntu vm and installed the app files_fulltedtsearch_tesseract in nextcloud with the help of my script. 
Now I want to enable files_fulltextsearch_tesseract and specify the settings with the help of an occ command like this:
`sudo -u www-data php /var/www/nextcloud/occ files_fulltextsearch_tesseract:configure "{\"tesseract_enabled\":\"1\",\"tesseract_lang\":\"eng,deu\"}"`
Unfortunatley this is not working. The message I get looks like this:
![grafik](https://user-images.githubusercontent.com/13244552/48580019-4a525300-e91e-11e8-9de4-48e6b24cd55c.png)
Then I tried it like displayed in the message:
`sudo -u www-data php /var/www/nextcloud/occ files_fulltextsearch:configure "{\"tesseract_enabled\":\"1\",\"tesseract_lang\":\"eng,deu\"}"`. It gives me the following in my console:
![grafik](https://user-images.githubusercontent.com/13244552/48580176-c5b40480-e91e-11e8-9d59-ad04dcb73f08.png)

I have also had a look at the database. The oc_appconfig table in nextcloud_db database does not contain any tesseract setting after installing the app via command line. Three records regarding tesseract are added after enabling the app via the webinterface. But I still can't change them on the command line.

So, the questions are: Is there a namespace defined for this app? What is the namespace? How can I enable the app and change the settings from command line / in a bash script?

Thanks for your answer in advance!

**Comment by daita** [comment]
please have a look to:

`./occ config:app:set --value '' files_fulltextsearch_tesseract tesseract_lang`
