### ISSUE TITLE
NC 15

### ISSUE THREAD

**Issue by Happyfeet01** [daita/files_fulltextsearch_tesseract#7]
Hello,

Can you Update this Plugin? It's not compatible with NC 15.

**Comment by ApoRes1337** [comment]
+1

**Comment by Raistlfiren** [comment]
bump as well

I installed the package manually by doing the following -
Going to the apps directory of NextCloud
Running - "git clone https://github.com/daita/files_fulltextsearch_tesseract.git"
Installing composer - https://getcomposer.org/download/
Running - "composer install"
Enabling the app in the backend from the Admin panel

It seems to work okay in version 15.
